# Generated by Django 4.2 on 2023-04-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=155)),
                ('cnpj_cpf', models.CharField(max_length=14, verbose_name='CNPJ/CPF')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=200)),
                ('numerocasa', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=15)),
            ],
        ),
    ]
